using Core.Domain.Enums;

namespace Core.Application.DTOs.Financeiro;

public sealed record ReceitaLogDto(long Id, DateOnly Data, AcaoLogs Acao, string Descricao);
public sealed record ReceitaAreaRateioDto(long AreaId, string AreaNome, long SubAreaId, string SubAreaNome, decimal? Valor);
public sealed record ReceitaDto(long Id, string Descricao, string? Observacao, DateOnly DataLancamento, DateOnly DataVencimento, DateOnly? DataEfetivacao, string TipoReceita, string TipoRecebimento, Recorrencia Recorrencia, int? QuantidadeRecorrencia, bool RecorrenciaFixa, decimal ValorTotal, decimal ValorLiquido, decimal Desconto, decimal Acrescimo, decimal Imposto, decimal Juros, decimal? ValorEfetivacao, string Status, IReadOnlyCollection<AmigoRateioDto> AmigosRateio, IReadOnlyCollection<ReceitaAreaRateioDto> AreasSubAreasRateio, string? ContaBancaria, IReadOnlyCollection<DocumentoDto> Documentos, IReadOnlyCollection<ReceitaLogDto> Logs);

public sealed record ReceitaAreaRateioRequest(long AreaId, long SubAreaId, decimal? Valor);
public sealed record CriarReceitaRequest(string Descricao, string? Observacao, DateOnly DataLancamento, DateOnly DataVencimento, string TipoReceita, string TipoRecebimento, Recorrencia Recorrencia, decimal ValorTotal, decimal Desconto, decimal Acrescimo, decimal Imposto, decimal Juros, IReadOnlyCollection<ReceitaAreaRateioRequest> AreasSubAreasRateio, string? ContaBancaria, IReadOnlyCollection<DocumentoRequest>? Documentos = null, IReadOnlyCollection<AmigoRateioRequest>? AmigosRateio = null, int? QuantidadeRecorrencia = null, bool RecorrenciaFixa = false, decimal? ValorLiquido = null);
public sealed record AtualizarReceitaRequest(string Descricao, string? Observacao, DateOnly DataLancamento, DateOnly DataVencimento, string TipoReceita, string TipoRecebimento, Recorrencia Recorrencia, decimal ValorTotal, decimal Desconto, decimal Acrescimo, decimal Imposto, decimal Juros, IReadOnlyCollection<ReceitaAreaRateioRequest> AreasSubAreasRateio, string? ContaBancaria, IReadOnlyCollection<DocumentoRequest>? Documentos = null, IReadOnlyCollection<AmigoRateioRequest>? AmigosRateio = null, int? QuantidadeRecorrencia = null, bool RecorrenciaFixa = false, decimal? ValorLiquido = null);
public sealed record EfetivarReceitaRequest(DateOnly DataEfetivacao, string TipoRecebimento, string? ContaBancaria, decimal ValorTotal, decimal Desconto, decimal Acrescimo, decimal Imposto, decimal Juros, IReadOnlyCollection<DocumentoRequest>? Documentos = null);
