using Core.Domain.Enums;

namespace Core.Application.DTOs.Financeiro;

public sealed record ListarReceitasRequest(string? Id, string? Descricao, string? Competencia, DateOnly? DataInicio, DateOnly? DataFim, bool VerificarUltimaRecorrencia);
public sealed record ReceitaLogDto(long Id, DateOnly Data, AcaoLogs Acao, string Descricao);
public sealed record ReceitaAreaRateioDto(long AreaId, string AreaNome, long SubAreaId, string SubAreaNome, decimal? Valor);

public sealed record ReceitaAreaRateioRequest(long AreaId, long SubAreaId, decimal? Valor);
public sealed record ReceitaListaDto(long Id, string Descricao, string Competencia, DateOnly DataLancamento, DateOnly DataVencimento, DateOnly? DataEfetivacao, TipoReceita TipoReceita, TipoRecebimento TipoRecebimento, decimal ValorTotal, decimal ValorLiquido, decimal? ValorEfetivacao, string Status, long? ContaBancariaId, long? ContaDestinoId, long? CartaoId);
public sealed record ReceitaDto(long Id, string Descricao, string? Observacao, string Competencia, DateOnly DataLancamento, DateOnly DataVencimento, DateOnly? DataEfetivacao, TipoReceita TipoReceita, TipoRecebimento TipoRecebimento, Recorrencia Recorrencia, int? QuantidadeRecorrencia, bool RecorrenciaFixa, decimal ValorTotal, decimal? ValorTotalRateioAmigos, decimal ValorLiquido, decimal Desconto, decimal Acrescimo, decimal Imposto, decimal Juros, decimal? ValorEfetivacao, string Status, IReadOnlyCollection<AmigoRateioDto> AmigosRateio, IReadOnlyCollection<ReceitaAreaRateioDto> AreasSubAreasRateio, long? ContaBancariaId, long? ContaDestinoId, long? CartaoId, IReadOnlyCollection<DocumentoDto> Documentos, IReadOnlyCollection<ReceitaLogDto> Logs);
public sealed record CriarReceitaRequest(string Descricao, string? Observacao, string? Competencia, DateOnly DataLancamento, DateOnly DataVencimento, TipoReceita TipoReceita, TipoRecebimento TipoRecebimento, Recorrencia Recorrencia, decimal ValorTotal, decimal Desconto, decimal Acrescimo, decimal Imposto, decimal Juros, IReadOnlyCollection<ReceitaAreaRateioRequest> AreasSubAreasRateio, IReadOnlyCollection<DocumentoRequest>? Documentos = null, IReadOnlyCollection<AmigoRateioRequest>? AmigosRateio = null, int? QuantidadeRecorrencia = null, bool RecorrenciaFixa = false, decimal? ValorLiquido = null, long? ContaBancariaId = null, long? ContaDestinoId = null, long? CartaoId = null, decimal? ValorTotalRateioAmigos = null, TipoRateioAmigos? TipoRateioAmigos = null);
public sealed record AtualizarReceitaRequest(string Descricao, string? Observacao, string? Competencia, DateOnly DataLancamento, DateOnly DataVencimento, TipoReceita TipoReceita, TipoRecebimento TipoRecebimento, Recorrencia Recorrencia, decimal ValorTotal, decimal Desconto, decimal Acrescimo, decimal Imposto, decimal Juros, IReadOnlyCollection<ReceitaAreaRateioRequest> AreasSubAreasRateio, IReadOnlyCollection<DocumentoRequest>? Documentos = null, IReadOnlyCollection<AmigoRateioRequest>? AmigosRateio = null, int? QuantidadeRecorrencia = null, bool RecorrenciaFixa = false, decimal? ValorLiquido = null, long? ContaBancariaId = null, long? ContaDestinoId = null, long? CartaoId = null, decimal? ValorTotalRateioAmigos = null, TipoRateioAmigos? TipoRateioAmigos = null);
public sealed record EfetivarReceitaRequest(DateOnly DataEfetivacao, TipoRecebimento TipoRecebimento, decimal ValorTotal, decimal Desconto, decimal Acrescimo, decimal Imposto, decimal Juros, IReadOnlyCollection<DocumentoRequest>? Documentos = null, long? ContaBancariaId = null, long? CartaoId = null, string? ObservacaoHistorico = null, long? ContaDestinoId = null);
public sealed record EstornarReceitaRequest(DateOnly DataEstorno, string? ObservacaoHistorico = null, bool OcultarDoHistorico = true, long? ContaDestinoId = null);
